🚀 진행도 컴포넌트(Progress Bar) 구현
5Duck-Lab/serengeti pull request #20
Opened 2023-11-18 17:30 UTC by okorion

## 어떤 일에 대한 PR인가요?
- Progress Bar 컴포넌트 구현에 대한 PR

## 변경사항에 대해 설명 해 주세요
- Progress Bar Style 변경 및 Checkpoint 클릭 시 Scroll 이동

## PR 관련하여 추가로 알아야 할 사항이 있나요?
- 현재 Checkpoint 클릭시 sectionRatio에 따라 화면이 이동하는데 Active Bar가 제대로 표시되지 않는 버그 존재
  - 추후 2D<->3D 전환 등의 기능이 구현될 때 scroll을 잠시 멈춰두는 기능 등 구현 방식에 따라 scroll 구현 또한 달라질 수도 있어서 이후에 버그 수정 예정

![image](https://github.com/5Duck-Lab/serengeti/assets/97646070/f82e31af-7df0-4279-ba02-d641cbaa50b8)

## 🙏 셀프체크 🙏
( x 를 넣어주세요)
- [x] dev에서 빌드가 문제없이 작동하나요?
- [x] PR의 changes에 대해 한번 더 검토했나요?
- [x] 불필요한 console 등 디버깅 코드는 제거했나요?
- [x] commit 컨벤션을 맞췄나요?
    + 🔧(fix), ♻️(refactoring), 🎨(style), 📝(docs), 🚀(feat), 🧪(test), 📦(chore), 📌(release)

2023-11-19 06:55 UTC, Joong-Sunny requested changes
+readme PR 따로 분리하면 더 좋을 것 같습니다

2023-11-19 06:55 UTC, Joong-Sunny commented on src/components/progressBar/ProgressBar.tsx
> +            checked={index <= scrollFactor * (sectionRefs.length - 1)}
요게 어떤뜻인가요?

2023-11-19 06:55 UTC, Joong-Sunny commented on src/hooks/use-smooth-scroll.ts
> +};
hook이 아닌데 hooks폴더에 넣으신 이유가 있나용

2023-11-19 06:55 UTC, Joong-Sunny commented on src/hooks/use-smooth-scroll.ts
> +export const useSmoothScrollToRef = () => {
훅이 아닌데 `use`접두어를 쓰면 사용시 혼란스러울 것 같습니다

2023-11-19 06:55 UTC, Joong-Sunny commented on src/components/progressBar/ProgressBarShape.tsx
> +  // background-color: rgba(0, 0, 0, 0.5);
주석 제거해도 될 것 같습니닷

2023-11-19 06:55 UTC, Joong-Sunny commented on src/components/progressBar/ProgressBar.tsx
> +  const smoothScrollToRef = useSmoothScrollToRef(); // 사용자 정의 스무스 스크롤 훅
훅이 아닌 것 같습니다.

2023-11-19 06:55 UTC, Joong-Sunny commented on src/components/progressBar/ProgressBar.tsx
> +    console.log(targetPosition);
console.log가 들어온 것 같습니다.

2023-11-19 06:56 UTC, Joong-Sunny commented
<img width="993" alt="image" src="https://github.com/5Duck-Lab/serengeti/assets/63194662/b1b6b49c-b6e4-4ccf-acb6-d76c36446ef6">

4번을 클릭하면, activeBar가 살짝 꼬리가 남기도 하는데, 이게 위에서 말씀하신 이슈인가요

2023-11-19 06:59 UTC, Joong-Sunny commented on src/components/progressBar/ProgressBar.tsx
> +        {sectionRefs.map((position, index) => (
사용되고 있지 않는 `position`이 남아있는 것 같습니다.

2023-11-19 07:04 UTC, Joong-Sunny commented on src/components/progressBar/ProgressBar.tsx
> +    if (!isNaN(targetPosition)) {
targetPosition이 Number가 아닌 상황이 생기기도 하나요

2023-11-19 07:15 UTC, Joong-Sunny commented on src/components/progressBar/ProgressBar.tsx
> +    if (!isNaN(targetPosition)) {
targetPosition이 Number가 아닌 상황이 생기기도 하나요

2023-11-19 07:15 UTC, Joong-Sunny commented on src/components/progressBar/ProgressBar.tsx
> +    if (!isNaN(targetPosition)) {
targetPosition에 number가 아닌값이 들어온다면, 타입스크립트를 사용중이니 type을 이용해서 체크해볼수도 있을 것 같습니다.

2023-11-19 07:15 UTC, Joong-Sunny commented on src/components/progressBar/ProgressBarActive.tsx
>  `;
요번 PR내용은 아니지만, 고치시면서 attr을 이용해서 width를 조절하는게 더 좋을 것 같습니다.
현재는 클래스 200개 생성 오류가 뜨는 것 같습니다.
[styled작동원리](https://medium.com/styled-components/how-styled-components-works-618a69970421)  에서 아랫부분에 `performance tips` 부분 보시면 자세히 나와있습니다

2023-11-19 07:16 UTC, Joong-Sunny commented on src/components/progressBar/ProgressBarActive.tsx
>  `;
<img width="1107" alt="image" src="https://github.com/5Duck-Lab/serengeti/assets/63194662/6c0563c3-1043-4904-8af8-2b279ada9dfa">

2023-11-19 07:26 UTC, Joong-Sunny requested changes
#8 에서의 커밋들 흘러들어온 것 같습니다. 제거 부탁드립니당

2023-11-19 13:54 UTC, okorion commented
내일 comment 다시 확인하고 다 고쳐보겠습니당 👾

2023-11-20 15:43 UTC, okorion commented
git rebase 실패 후 많은 commit이 쌓여서 close

2023-11-20 15:43 UTC, closed without merging

2023-11-20 16:11 UTC, okorion commented on src/components/progressBar/ProgressBar.tsx
> +            checked={index <= scrollFactor * (sectionRefs.length - 1)}
checkpoint는 progressBar 컴포넌트의 동그란 부분이고 scrollFactor(0~1)에 (총 섹션의 수 -1)만큼 곱해서 checkpoint가 index에 맞춰서 on(노란색 채워지도록) 될 수 있도록 checked해주는 로직입니다.

2023-11-20 17:00 UTC, okorion commented on src/components/progressBar/ProgressBar.tsx
> +    if (!isNaN(targetPosition)) {
0부터 1까지 number만 받는거 확인하여 고쳤습니닷 :O

2023-11-20 17:04 UTC, okorion commented on src/components/progressBar/ProgressBar.tsx
> +        {sectionRefs.map((position, index) => (
position을 없애니
![image](https://github.com/5Duck-Lab/serengeti/assets/97646070/cf272273-95e8-4589-bbdd-cd63f81e8df3)

![image](https://github.com/5Duck-Lab/serengeti/assets/97646070/a9c82134-88d0-4c18-9498-11d4a2603344)

![image](https://github.com/5Duck-Lab/serengeti/assets/97646070/585b71f9-5dfa-499c-a984-3a48afae8587)

요렇게 되네요 😂

2023-11-20 17:17 UTC, okorion commented on src/components/progressBar/ProgressBarActive.tsx
>  `;
![image](https://github.com/5Duck-Lab/serengeti/assets/97646070/17b3592f-b52e-40f0-81b7-050f5b51e3a8)
라고 챗선생이 말하긴하고,
![image](https://github.com/5Duck-Lab/serengeti/assets/97646070/176d5390-c80a-4662-8638-abee2b2cb479)
와 같이 코드를 작성해서 테스트도 해보았는데 progress의 active bar의 반응이 매우 느려져서 그대로 적용시키려고합니다!
 내일 클래스 200개 생성 경고를 한 번 더 고쳐보겠습니닸 :O