🚀 진행도 컴포넌트(Progress Bar) 구현 - 피드백 부분 반영
5Duck-Lab/serengeti pull request #21
Opened 2023-11-20 17:27 UTC by okorion

## 어떤 일에 대한 PR인가요?
- Progress Bar 컴포넌트 구현에 대한 PR

## 변경사항에 대해 설명 해 주세요
- Progress Bar Style 변경 및 Checkpoint 클릭 시 Scroll 이동

## PR 관련하여 추가로 알아야 할 사항이 있나요?
- 현재 Checkpoint 클릭시 sectionRatio에 따라 화면이 이동하는데 Active Bar가 제대로 표시되지 않는 버그 존재
  - 추후 2D<->3D 전환 등의 기능이 구현될 때 scroll을 잠시 멈춰두는 기능 등 구현 방식에 따라 scroll 구현 또한 달라질 수도 있어서 이후에 버그 수정 예정

![image](https://github.com/5Duck-Lab/serengeti/assets/97646070/f82e31af-7df0-4279-ba02-d641cbaa50b8)

## 🙏 셀프체크 🙏
( x 를 넣어주세요)
- [x] dev에서 빌드가 문제없이 작동하나요?
- [x] PR의 changes에 대해 한번 더 검토했나요?
- [x] 불필요한 console 등 디버깅 코드는 제거했나요?
- [x] commit 컨벤션을 맞췄나요?
    + 🔧(fix), ♻️(refactoring), 🎨(style), 📝(docs), 🚀(feat), 🧪(test), 📦(chore), 📌(release)

2023-11-22 02:31 UTC, Joong-Sunny requested changes
rebase성공하신건가요..! 커밋 깔끔하고 좋네요👍

2023-11-22 02:31 UTC, Joong-Sunny commented on src/components/progressBar/ProgressBarActive.tsx
> +  z-index: 1;
#20 에서 [저번에 남겨주신 댓글](https://github.com/5Duck-Lab/serengeti/pull/20#discussion_r1399516776) 보고 똑같이 attr이용해보았는데 속도에는 문제가 없는 것 같습니다. 

실제로 클래스를 만들 필요가 없으니 오히려 더 빨라져야 하지 않을까 싶기도 합니다. 혹시 어떻게 느려지는지 조금 더 알 수 있을까여

2023-11-22 02:31 UTC, Joong-Sunny commented on src/components/progressBar/ProgressBarActive.tsx
> +  z-index: 1;
그리고 `scrollWidth`속성이 없어서 에러가 뜨는 것 같습니닷, `transient props`로 바꿔주시면 더 좋을 것 같아영

<img width="608" alt="image" src="https://github.com/5Duck-Lab/serengeti/assets/63194662/691ab9f0-ee3c-41d9-b946-f059c59fd501">

2023-11-29 15:02 UTC, okorion commented on src/components/progressBar/ProgressBarActive.tsx
> +  z-index: 1;
내일 저녁에 후딱 고쳐서 PR 날려보겠습니당 👍

2023-12-03 16:18 UTC, okorion commented
내일은 꼭 🥸

2023-12-04 12:24 UTC, okorion commented on src/components/progressBar/ProgressBarActive.tsx
> +  z-index: 1;
> #20 에서 [저번에 남겨주신 댓글](https://github.com/5Duck-Lab/serengeti/pull/20#discussion_r1399516776) 보고 똑같이 attr이용해보았는데 속도에는 문제가 없는 것 같습니다.
> 
> 실제로 클래스를 만들 필요가 없으니 오히려 더 빨라져야 하지 않을까 싶기도 합니다. 혹시 어떻게 느려지는지 조금 더 알 수 있을까여

예전 노트북이 시름시름 앓아서 애초에 느렸던거 같네요!! 다른 컴퓨터로 실행하니 잘 됩니다!!

2023-12-04 12:24 UTC, okorion commented on src/components/progressBar/ProgressBarActive.tsx
> +  z-index: 1;
> 그리고 `scrollWidth`속성이 없어서 에러가 뜨는 것 같습니닷, `transient props`로 바꿔주시면 더 좋을 것 같아영
> 

오오오 transient props 써서 고쳤습니닷!

2023-12-04 12:53 UTC, okorion commented
현재 `scrollwidth` 콘솔 에러와 200 Classes 초과 생성 에러 잡았고 Merge된 상태로 commit 올려놓은 상태입니다!

2023-12-04 12:53 UTC, okorion commented
내일 모각코에서 진행도 컴포넌트 우측 하단 fix시켜볼게요!

2023-12-05 10:32 UTC, Joong-Sunny approved these changes
LGTM!

2023-12-05 10:36 UTC, merged