feat : mailto를 이용한 mail 보내기 기능 추가 및 section2 오른쪽으로 위치 변경
5Duck-Lab/serengeti pull request #22
Opened 2023-11-25 12:34 UTC by YooJinHa96

## 어떤 일에 대한 PR인가요?

## 변경사항에 대해 설명 해 주세요

## PR 관련하여 추가로 알아야 할 사항이 있나요?

## 🙏 셀프체크 🙏
( x 를 넣어주세요)
- [ ] dev에서 빌드가 문제없이 작동하나요?
- [ ] PR의 changes에 대해 한번 더 검토했나요?
- [ ] 불필요한 console 등 디버깅 코드는 제거했나요?
- [ ] commit 컨벤션을 맞췄나요?
    + 🔧(fix), ♻️(refactoring), 🎨(style), 📝(docs), 🚀(feat), 🧪(test), 📦(chore), 📌(release)

2023-11-25 16:16 UTC, Joong-Sunny requested changes

2023-11-25 16:16 UTC, Joong-Sunny commented on src/page/Section5.tsx
> +    console.log(email);
콘솔 흘러들어온 것 같습니닷

2023-11-25 16:16 UTC, Joong-Sunny commented on src/page/Section2.tsx
> +
공백 빼도 될것 같습니다

2023-11-25 16:16 UTC, Joong-Sunny commented on src/page/Section2.tsx
> +
공백 제거해도 될 것 같습니닷

2023-11-25 16:16 UTC, Joong-Sunny commented on src/constants/useProfile.ts
> +    '안녕하세요, 저는 Serengeti 개발자 축얌입니다..\n지금부터 제 소개를 시작해볼까 합니다.\n저에 대해 더 알고 싶으시다면\nScroll을 내려주세요.',
명시적으로 \n 넣어주어야 되는거죠? 그냥 줄바꿈으로는 세렝귀티 화면에 보여질때 줄바꿈 안먹는 건가여? [template literal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#multi-line_strings)로 줄바꿈 될것 같기도 해서요 (multi line string)

2023-11-25 16:16 UTC, Joong-Sunny commented on src/App.tsx
> +// import { useScrollPosition } from '@/hooks/use-scroll-position';
`App.tsx` 파일에  불필요한 주석이 많이들어온 것 같습니닷

2023-11-25 16:25 UTC, YooJinHa96 commented on src/page/Section5.tsx
> +    console.log(email);
헉 얘는 지워서 올리겠습니다.

2023-11-25 16:26 UTC, YooJinHa96 commented on src/App.tsx
> +// import { useScrollPosition } from '@/hooks/use-scroll-position';
얘는 현규님 progress bar에 주석처리하면서, 안쓰는애들인데 그냥 지워버릴까여??/

2023-11-25 16:27 UTC, YooJinHa96 commented on src/constants/useProfile.ts
> +    '안녕하세요, 저는 Serengeti 개발자 축얌입니다..\n지금부터 제 소개를 시작해볼까 합니다.\n저에 대해 더 알고 싶으시다면\nScroll을 내려주세요.',
ㅇㅎ ` ` 좋은 정보 감사합니다. 처음 들어봤는데, 한번 확인해볼게영.

2023-11-25 16:57 UTC, Joong-Sunny approved these changes
LGTM!

2023-11-25 16:57 UTC, merged

2023-11-26 14:58 UTC, okorion commented
LGTM!